#!/usr/local/bin/zsh

# Filename: clean
# Modified: June 21, 2019 08:51:52 AM
# Author:   David Oniani
# License:  GNU General Public License v3.0


# 2015 Quarter 2
python3 clean.py --path=./data/csv/year-2015/2015-Quarter-2.csv

# 2015 Quarter 3
python3 clean.py --path=./data/csv/year-2015/2015-Quarter-3.csv

# 2015 Quarter 4
python3 clean.py --path=./data/csv/year-2015/2015-Quarter-4.csv

# 2016 Quarter 1
python3 clean.py --path=./data/csv/year-2016/2016-Quarter-1.csv

# 2016 Quarter 2
python3 clean.py --path=./data/csv/year-2016/2016-Quarter-2.csv

# 2016 Quarter 3
python3 clean.py --path=./data/csv/year-2016/2016-Quarter-3.csv

# 2016 Quarter 4
python3 clean.py --path=./data/csv/year-2016/2016-Quarter-4.csv

# 2017 Quarter 1
python3 clean.py --path=./data/csv/year-2017/2017-Quarter-1.csv

# 2017 Quarter 2 May
python3 clean.py --path=./data/csv/year-2017/2017-Quarter-2-May.csv

# 2017 Quarter 2 April
python3 clean.py --path=./data/csv/year-2017/2017-Quarter-2-April.csv

# 2017 Quarter 3
python3 clean.py --path=./data/csv/year-2017/2017-Quarter-3.csv
