#!/usr/local/bin/zsh

# Filename:     barchart
# Modified:     August 13, 2019 10:49:52 PM
# Author:       David Oniani
# License:      GNU General Public License v3.0
# Descriptinon: A script to plot a barchart

# Cleanup
printf "Cleanup...\n"
rm -fr __pycache__
rm -fr barchart-plots

# Creating plots
printf "Creating barchart plots...\n"
python3 age_targeted.py
python3 count_words.py
python3 distribution_of_posts.py

# Move to appropriate directories
printf "Creating directories...\n"
mkdir barchart-plots
printf "Moving files to barchart-plots directory...\n"
mv *.png barchart-plots
printf "Done!\n"
